### ISSUE TITLE
Weeman 

### ISSUE THREAD

**Issue by batasu** [farhansadik/echominal-development#1]
```python
Traceback (most recent call last):
  File "/home/kali/.config/echominal/scripts/weeman/weeman.py", line 63, in <module>
    main()
  File "/home/kali/.config/echominal/scripts/weeman/weeman.py", line 60, in main
    shell()
  File "/home/kali/.config/echominal/scripts/weeman/core/shell.py", line 103, in shell
    print_startup()
  File "/home/kali/.config/echominal/scripts/weeman/core/shell.py", line 34, in print_startup
    sys.stdout.write(open("core/logo.txt", "r").read()[:-1])
IOError: [Errno 2] No such file or directory: 'core/logo.txt'

```

**Comment by farhansadik** [comment]
### Patch 0.1.22
Installation Result : 
```
You want to install weeman [y/n] y
Cloning into '/data/data/com.termux/files/home/.config/echominal/scripts/weeman'...
remote: Enumerating objects: 54, done.
remote: Total 54 (delta 0), reused 0 (delta 0), pack-reused 54
Receiving objects: 100% (54/54), 134.13 KiB | 360.00 KiB/s, done.
Resolving deltas: 100% (5/5), done.
Error: %s
```
Run Result: 
```
echominal@linux $ 1

 [*] checking for weeman
 [*] found weeman
 [*] ready to run weeman
Error: %s
```

**Comment by squaredevops** [comment]
### Patch 0.1.24
### Fixed & Worked 

```
___       ___       ___       ___       ___       ___
   /\__\     /\  \     /\  \     /\__\     /\  \     /\__\
  /:/\__\   /::\  \   /::\  \   /::L_L_   /::\  \   /:| _|_
 /:/:/\__\ /::\:\__\ /::\:\__\ /:/L:\__\ /::\:\__\ /::|/\__\
 \::/:/  / \:\:\/  / \:\:\/  / \/_/:/  / \/\::/  / \/|::/  /
  \::/  /   \:\/  /   \:\/  /    /:/  /    /:/  /    |:/  /
   \/__/     \/__/     \/__/     \/__/     \/__/     \/__/
          .:[ Weeman last version (1.7.1-end) ]:.
weeman > quit
[03:28:19] bye bye!

Press [Enter] key to continue...
```
